---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/public_api/v1/categories":
    get:
      summary: list categories
      responses:
        '200':
          description: successful
    post:
      summary: create category
      responses:
        '200':
          description: successful
  "/public_api/v1/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update category
      responses:
        '200':
          description: successful
    put:
      summary: update category
      responses:
        '200':
          description: successful
    delete:
      summary: delete category
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
